license_id: cc-by
methodology: Registry
caveats: This dataset is refreshed every week, but the source datasets may have different update schedules. Please refer to the [source datasets](https://data.humdata.org/dataset/?dataseries_name=WFP+-+Rainfall+Indicators+at+Subnational+Level) to verify their specific update frequency.
dataset_source: Climate Hazards Center UC Santa Barbara & WFP
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org:  hdx-hapi
data_update_frequency: 7
notes: |
  This dataset contains data obtained from the
  [HDX Humanitarian API](https://hapi.humdata.org/) (HDX HAPI),
  which provides standardized humanitarian indicators designed
  for seamless interoperability from multiple sources.
  The data facilitates automated workflows and visualizations
  to support humanitarian decision making.
  For more information, please see the HDX HAPI
  [landing page](https://data.humdata.org/hapi)
  and
  [documentation](https://hdx-hapi.readthedocs.io/en/latest/).

  Warnings typically indicate corrections have been made to
  the data or show things to look out for. Rows with only warnings
  are considered complete, and are made available via the API.
  Errors usually mean that the data is incomplete or unusable.
  Rows with any errors are not present in the API but are included
  here for transparency.

  Note that this dataset only contains admin one data for non
  HRP/GHO countries. For all other countries both admin one and two
  are present (where available). For the time being only the current
  year of rainfall data is included due to the size of the data.
  For the full set of data, please visit the
  [source datasets](https://data.humdata.org/dataset/?dataseries_name=WFP+-+Rainfall+Indicators+at+Subnational+Level).
subnational: "1"
dataset_preview: no_preview
