# Collector specific configuration

resource_name: "Global Climate: Rainfall ({ytd} year(s) ago)"

resource_description: "Rainfall data ({ytd} year(s) ago) from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/climate/#rainfall) for more information"

headers:
  - location_code
  - has_hrp
  - in_gho
  - provider_admin1_name
  - provider_admin2_name
  - admin1_code
  - admin1_name
  - admin2_code
  - admin2_name
  - admin_level
  - provider_admin1_code
  - provider_admin2_code
  - aggregation_period
  - rainfall
  - rainfall_long_term_average
  - rainfall_anomaly_pct
  - number_pixels
  - version
  - reference_period_start
  - reference_period_end
  - dataset_hdx_id
  - resource_hdx_id
  - warning
  - error

tags:
  - "climate-weather"
