# Collector specific configuration

resource_info:
  name: "Global Climate: Rainfall"
  description: "Ranfall data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/climate/#rainfall) for more information"

hxl_tags:
  location_code: "#country+code"
  has_hrp: "#meta+has_hrp"
  in_gho: "#meta+in_gho"
  provider_admin1_name: "#adm1+name+provider"
  provider_admin2_name: "#adm2+name+provider"
  admin1_code: "#adm1+code"
  admin1_name: "#adm1+name"
  admin2_code: "#adm2+code"
  admin2_name: "#adm2+name"
  admin_level: "#adm+level"
  wfp_id: "#adm+code+wfp"
  time_period: "#time+period"
  rainfall: "#rainfall"
  rainfall_long_term_average: "#rainfall+lta"
  rainfall_anomaly_pct: "#rainfall+anomaly+pct"
  reference_period_start: "#date+start"
  reference_period_end: "#date+end"
  dataset_hdx_id: "#meta+dataset_id"
  resource_hdx_id: "#meta+resource_id"
  warning: "#meta+warning"
  error: "#meta+error"

tags:
  - "climate-weather"
  - "hxl"
